import type { ComparisonResult, MeasurementSession, ScoreResult } from "@lanternajs/core";
import { categoryLabel, formatMetricValue, metricLabel } from "./format";

function statusEmoji(category: string): string {
	switch (category) {
		case "good":
			return "\u{1F7E2}";
		case "needs_work":
			return "\u{1F7E1}";
		case "poor":
			return "\u{1F534}";
		default:
			return "";
	}
}

function deltaArrow(delta: number): string {
	if (delta > 0) return "\u2B06";
	if (delta < 0) return "\u2B07";
	return "";
}

function formatDelta(delta: number): string {
	const sign = delta > 0 ? "+" : "";
	return `${sign}${delta}`;
}

/**
 * Format a performance report as GitHub-flavored Markdown, suitable for PR comments.
 * Optionally includes a comparison section when a ComparisonResult is provided.
 * Optionally includes Tier 3 data (navigation, network) when a session is provided.
 */
export function formatMarkdownReport(
	score: ScoreResult,
	comparison?: ComparisonResult,
	session?: MeasurementSession,
): string {
	const lines: string[] = [];

	// Header
	lines.push("## \u{1F526} Lanterna Performance Report");
	lines.push("");
	lines.push(`**Score: ${score.overall} / 100** (${categoryLabel(score.category)})`);
	lines.push("");

	// Metrics table
	lines.push("### Metrics");
	lines.push("");
	lines.push("| Metric | Value | Score | Status |");
	lines.push("|--------|-------|-------|--------|");

	for (const metric of score.perMetric) {
		const label = metricLabel(metric.type);
		const value = formatMetricValue(metric.type, metric.value);
		const emoji = statusEmoji(metric.category);
		lines.push(`| ${label} | ${value} | ${metric.score} | ${emoji} |`);
	}

	// Comparison section (only if provided)
	if (comparison) {
		lines.push("");
		lines.push("### Comparison (vs baseline)");
		lines.push("");
		lines.push("| Metric | Previous | Current | Delta |");
		lines.push("|--------|----------|---------|-------|");

		for (const d of comparison.deltas) {
			const label = metricLabel(d.type);
			const prev = formatMetricValue(d.type, d.previous);
			const curr = formatMetricValue(d.type, d.current);
			const arrow = deltaArrow(d.delta);
			const deltaStr = formatDelta(d.delta);
			const regressionMark = d.status === "regressed" ? " \u{1F534}" : "";
			lines.push(`| ${label} | ${prev} | ${curr} | ${arrow} ${deltaStr}${regressionMark} |`);
		}

		lines.push("");
		if (comparison.hasRegression) {
			const plural = comparison.regressionCount > 1 ? "s" : "";
			lines.push(`\u26A0\uFE0F **${comparison.regressionCount} regression${plural} detected**`);
		} else {
			lines.push("\u2705 **No regressions detected**");
		}
	}

	// Navigation section (only if session has navigation data)
	if (session?.navigationTimeline) {
		const nav = session.navigationTimeline;
		lines.push("");
		lines.push("### Navigation Timeline");
		lines.push("");
		lines.push("| Screen | TTID | Render | Time |");
		lines.push("|--------|------|--------|------|");

		for (const screen of nav.screens) {
			const ttid = screen.ttid !== undefined ? `${Math.round(screen.ttid)}ms` : "N/A";
			const render =
				screen.renderDuration !== undefined ? `${Math.round(screen.renderDuration)}ms` : "N/A";
			const time =
				screen.timeOnScreen !== undefined ? `${(screen.timeOnScreen / 1000).toFixed(1)}s` : "N/A";
			lines.push(`| ${screen.screenName} | ${ttid} | ${render} | ${time} |`);
		}
	}

	// Network section (only if session has network data)
	if (session?.networkRequests && session.networkRequests.length > 0) {
		const requests = session.networkRequests;
		lines.push("");
		lines.push("### Network Summary");
		lines.push("");
		lines.push(`${requests.length} requests during session.`);
		const slow = requests.filter((r) => r.duration !== undefined && r.duration > 3000);
		if (slow.length > 0) {
			lines.push(`${slow.length} slow request${slow.length > 1 ? "s" : ""} (> 3s).`);
		}
	}

	// Footer
	lines.push("");
	lines.push("---");
	lines.push("*Generated by [Lanterna](https://github.com/user/lanterna) v0.0.1*");

	return lines.join("\n");
}
